export const COMMANDS = {
  UP: 'up',
  LS: 'ls',
  CD: 'cd',
  CAT: 'cat',
  ADD: 'add',
  RN: 'rn',
  CP: 'cp',
  MV: 'mv',
  HASH: 'hash',
  OS_EOL: 'os --EOL',
  OS_CPUS: 'os --cpus',
  OS_HOMEDIR: 'os --homedir',
  OS_username: 'os --username',
  OS_ARCH: 'os --architecture',
}
